/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package com.fearlanguage.knowledgegraph.gui;

import com.fearlanguage.knowledgegraph.KnowledgeGraphPreferences;
import org.openide.util.NbBundle;
import org.sleuthkit.autopsy.casemodule.Case;

/**
 *
 * @author Allan
 */
public class KnowledgeGraphOptionsPanel extends javax.swing.JPanel {
private static final long serialVersionUID = 1L;

    // Added by hand (not via the Form editor) to avoid GroupLayout surgery: an
    // opt-in toggle for insecure SSL. Required for some FEAR endpoints (e.g.
    // self-signed development certificates); applies to both the HTTP submission
    // and the embedded JCEF browser.
    private javax.swing.JCheckBox allowInsecureSsl;

    // Opt-in toggle for the diagnostic message dialogs (logging always happens).
    private javax.swing.JCheckBox showDiagnostics;

    // Notice shown at the top when no case is open (settings are per-case).
    private javax.swing.JLabel caseNoticeLabel;

    KnowledgeGraphOptionsPanel(KnowledgeGraphOptionsPanelController controller) {
        try {
            initComponents();

            allowInsecureSsl = new javax.swing.JCheckBox(
                    "Allow insecure SSL / trust all certificates (required for some FEAR endpoints)");
            showDiagnostics = new javax.swing.JCheckBox(
                    "Show diagnostic dialogs on errors (recommended while testing)");

            caseNoticeLabel = new javax.swing.JLabel(
                    "These settings apply to the currently open case. Open a case to edit them.");
            caseNoticeLabel.setForeground(java.awt.Color.RED);
            caseNoticeLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 8, 6, 8));
            caseNoticeLabel.setVisible(false);

            javax.swing.JPanel southToggles = new javax.swing.JPanel();
            southToggles.setLayout(new javax.swing.BoxLayout(southToggles, javax.swing.BoxLayout.Y_AXIS));
            southToggles.add(allowInsecureSsl);
            southToggles.add(showDiagnostics);

            removeAll();
            setLayout(new java.awt.BorderLayout());
            add(caseNoticeLabel, java.awt.BorderLayout.NORTH);
            add(jScrollPane1, java.awt.BorderLayout.CENTER);
            add(southToggles, java.awt.BorderLayout.SOUTH);
        } catch (Throwable ex) {
            com.fearlanguage.knowledgegraph.Diagnostics.reportError(
                    "Failed to build the Knowledge Graph options panel.", ex);
        }
    }

    /**
     * Enables or disables all editable inputs. Used to make the panel read-only
     * when no case is open, since the settings are per-case.
     */
    private void setInputsEnabled(boolean enabled) {
        knowledgeGraphApiUrl.setEnabled(enabled);
        knowledgeGraphUiUrl.setEnabled(enabled);
        oAuthClientId.setEnabled(enabled);
        oauthAuhtorizeEndpoint.setEnabled(enabled);
        oauthTokenEndpoint.setEnabled(enabled);
        oAuthScope.setEnabled(enabled);
        fearCaseName.setEnabled(enabled);
        allowInsecureSsl.setEnabled(enabled);
        // The diagnostics toggle is global, so it stays editable regardless.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        descriptionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        knowledgeGraphApiUrl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        knowledgeGraphUiUrl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        oAuthClientId = new javax.swing.JTextField();
        oauthAuhtorizeEndpoint = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        oauthTokenEndpoint = new javax.swing.JTextField();
        oAuthScope = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fearCaseName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel1.text")); // NOI18N

        jScrollPane1.setBorder(null);

        org.openide.awt.Mnemonics.setLocalizedText(descriptionLabel, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.descriptionLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel2.text")); // NOI18N

        knowledgeGraphApiUrl.setText(org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.text")); // NOI18N
        knowledgeGraphApiUrl.setName(""); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel3.text")); // NOI18N

        knowledgeGraphUiUrl.setText(org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.knowledgeGraphUiUrl.text")); // NOI18N
        knowledgeGraphUiUrl.setName(""); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel4.text")); // NOI18N

        oAuthClientId.setText(org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.oAuthClientId.text")); // NOI18N
        oAuthClientId.setName(""); // NOI18N

        oauthAuhtorizeEndpoint.setText(org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.oauthAuhtorizeEndpoint.text")); // NOI18N
        oauthAuhtorizeEndpoint.setName(""); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel6.text")); // NOI18N

        oauthTokenEndpoint.setText(org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.oauthTokenEndpoint.text")); // NOI18N
        oauthTokenEndpoint.setName(""); // NOI18N

        oAuthScope.setText(org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.oAuthScope.text")); // NOI18N
        oAuthScope.setName(""); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel7.text")); // NOI18N

        fearCaseName.setText(org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.fearCaseName.text")); // NOI18N
        fearCaseName.setName(""); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(KnowledgeGraphOptionsPanel.class, "KnowledgeGraphOptionsPanel.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(knowledgeGraphApiUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(knowledgeGraphUiUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(oauthAuhtorizeEndpoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(oAuthClientId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(oAuthScope, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(oauthTokenEndpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fearCaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(knowledgeGraphUiUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fearCaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(knowledgeGraphApiUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(oAuthClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(oAuthScope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(oauthAuhtorizeEndpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(oauthTokenEndpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        try {
            // Settings are per-case: only allow editing when a case is open.
            boolean caseOpen = Case.isCaseOpen();
            setInputsEnabled(caseOpen);
            caseNoticeLabel.setVisible(!caseOpen);

            knowledgeGraphApiUrl.setText(KnowledgeGraphPreferences.getKnowledgeGraphApi());
            knowledgeGraphUiUrl.setText(KnowledgeGraphPreferences.getKnowledgeGraphUi());
            oAuthClientId.setText(KnowledgeGraphPreferences.getOAuthClientId());
            oauthAuhtorizeEndpoint.setText(KnowledgeGraphPreferences.getOAuthAuthorizeEndpoint());
            oauthTokenEndpoint.setText(KnowledgeGraphPreferences.getOAuthTokenEndpoint());
            oAuthScope.setText(KnowledgeGraphPreferences.getOAuthScope());

            fearCaseName.setText(KnowledgeGraphPreferences.getFearCaseName());

            allowInsecureSsl.setSelected(KnowledgeGraphPreferences.getAllowInsecureSsl());
            showDiagnostics.setSelected(KnowledgeGraphPreferences.getShowDiagnosticDialogs());
        } catch (Throwable ex) {
            com.fearlanguage.knowledgegraph.Diagnostics.reportError(
                    "Failed to load the Knowledge Graph settings.", ex);
        }
    }

    void store() {
      try {
        // The connection settings are per-case; only persist them when a case is
        // open (the global diagnostics toggle is always saved). This avoids
        // silently writing per-case settings as global defaults from this dialog.
        if (Case.isCaseOpen()) {
            KnowledgeGraphPreferences.setKnowledgeGraphApi(knowledgeGraphApiUrl.getText());
            KnowledgeGraphPreferences.setKnowledgeGraphUi(knowledgeGraphUiUrl.getText());

            KnowledgeGraphPreferences.setOAuthClientId(oAuthClientId.getText());
            KnowledgeGraphPreferences.setOAuthAuthorizeEndpoint(oauthAuhtorizeEndpoint.getText());
            KnowledgeGraphPreferences.setOAuthTokenEndpoint(oauthTokenEndpoint.getText());
            KnowledgeGraphPreferences.setOAuthScope(oAuthScope.getText());

            KnowledgeGraphPreferences.setFearCaseName(fearCaseName.getText());

            KnowledgeGraphPreferences.setAllowInsecureSsl(allowInsecureSsl.isSelected());
        }

        KnowledgeGraphPreferences.setShowDiagnosticDialogs(showDiagnostics.isSelected());

        // Reflect any configuration change in the toolbar/menu action's enabled
        // state immediately (it is disabled until the case is configured).
        com.fearlanguage.knowledgegraph.actions.OpenAction.refreshEnabled();
      } catch (Throwable ex) {
        com.fearlanguage.knowledgegraph.Diagnostics.reportError(
                "Failed to save the Knowledge Graph settings.", ex);
      }
    }

    /**
     * @return true, since there is no way for this form to be invalid
     */
    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField fearCaseName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField knowledgeGraphApiUrl;
    private javax.swing.JTextField knowledgeGraphUiUrl;
    private javax.swing.JTextField oAuthClientId;
    private javax.swing.JTextField oAuthScope;
    private javax.swing.JTextField oauthAuhtorizeEndpoint;
    private javax.swing.JTextField oauthTokenEndpoint;
    // End of variables declaration//GEN-END:variables
}
